openapi: 3.0.3
info:
  title: products
  version: 1.0.0-SNAPSHOT
paths:
  /products:
    get:
      tags:
        - Rest Api
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            format: int32
            minimum: 0
            type: integer
          examples:
            mock1:
              value: 1
        - name: skip
          in: query
          required: true
          schema:
            format: int32
            minimum: 0
            type: integer
          examples:
            mock1:
              value: 1
      responses:
        "200":
          description: Genera una lista de productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
              examples:
                mock1:
                  value: |-
                    {"products": [
                      { "id": 2,
                        "title": "iPhone X",
                        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
                        "price": 899,
                        "discountPercentage": 17.94,
                        "rating": 4.44,
                        "stock": 34,
                        "brand": "Apple",
                        "category": "smartphones",
                        "thumbnail": "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg"
                      }
                    ]}
components:
  schemas:
    ProductList:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Products'
    Products:
      type: object
      properties:
        id:
          format: int32
          type: integer
        title:
          type: string
        description:
          type: string
        price:
          format: double
          type: number
        discountPercentage:
          format: double
          type: number
        stock:
          format: int32
          type: integer
        brand:
          type: string
        category:
          type: string
        thumbnail:
          type: string
      required:
        - id
        - stock
        - brand
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
